version: '3.8'

services:
  frontend:
    build:
      context: ./chatapp
      args:
        - VITE_API_HOST=backend
        - VITE_API_PORT=8000
        - VITE_APP_TITLE="LocalRAG Chat"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./chatapp/chatapp-cert.pem:/etc/nginx/ssl/chatapp-cert.pem:ro
      - ./chatapp/chatapp-key.pem:/etc/nginx/ssl/chatapp-key.pem:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGINS=http://localhost,http://127.0.0.1
      # - MONGODB_USER=root
      # - MONGODB_PASSWORD=password
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - DB_TYPE=mongodb
    depends_on:
      - chroma
      - mongo

  chroma:
    image: chromadb/chroma:1.0.12 
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma

  mongo:
    image: mongo:8.0.10
    ports:
      - "8081:8081"
      - "27017:27017"
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    volumes:
      - ./mongo_data:/data/db